# Generated by Django 3.2.9 on 2021-11-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_auto_20211119_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='image_link',
            field=models.TextField(null=True),
        ),
    ]
