# Generated by Django 3.2.9 on 2021-11-19 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0004_auto_20211119_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Разделы', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
    ]
