# Generated by Django 3.2.9 on 2021-11-19 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0005_auto_20211119_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_info', models.TextField(null=True)),
                ('correct_answer', models.CharField(max_length=10, null=True)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='topics.topic')),
            ],
            options={
                'verbose_name': 'Задания',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
