# Generated by Django 3.2.9 on 2021-11-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_alter_topic_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['topic'], 'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['section'], 'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
    ]
