# Generated by Django 3.2.9 on 2021-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_auto_20211120_1240'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['section', 'time_create'], 'verbose_name': 'Темы', 'verbose_name_plural': 'Темы'},
        ),
        migrations.AddField(
            model_name='section',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
