# Generated by Django 3.2.9 on 2021-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0010_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
    ]
